//! The build information that only the JavaScript side knows.
//!
//! The `build.rs` script of pirate must never run bun, npm, or Vite. Two of the
//! six values in `pirate --version --long` come from the installed npm package:
//! the ghostty-web version and the SHA-256 of the wasm module. Stage 1 writes
//! them to `web/build-info.toml`, and `build.rs` reads that file.

use crate::{toolchain, Result};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

/// Where the data URI starts inside the ESM file of ghostty-web.
const DATA_URI: &str = "data:application/wasm;base64,";

/// Collect the values from `web/node_modules` and write `web/build-info.toml`.
/// Returns the path of the generated file.
pub fn write(web: &Path) -> Result<PathBuf> {
    let package = web.join("node_modules/ghostty-web");
    if !package.is_dir() {
        return Err(format!("ghostty-web is not installed at {}", package.display()).into());
    }

    let manifest: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(package.join("package.json"))?)?;
    let version = manifest
        .get("version")
        .and_then(|v| v.as_str())
        .ok_or("the package.json of ghostty-web has no `version`")?
        .to_string();

    // ghostty-web ships the module twice: as a file, and as a base64 data URI
    // inside the ESM bundle. The browser loads the data URI first, so hash the
    // file and then make sure that the two forms hold the same bytes.
    let wasm = package.join("ghostty-vt.wasm");
    if !wasm.is_file() {
        return Err(format!("no wasm module at {}", wasm.display()).into());
    }
    let sha256 = toolchain::sha256_file(&wasm)?;
    compare_inlined(&package.join("dist/ghostty-web.js"), &sha256)?;

    let out = web.join("build-info.toml");
    let body = format!(
        "# Generated by `cargo xtask web`. Do not edit.\n\
         #\n\
         # The `build.rs` script of pirate must not run bun, npm, or Vite, so\n\
         # stage 1 writes these two values here and `build.rs` reads them.\n\
         ghostty_web_version = \"{version}\"\n\
         wasm_sha256 = \"{sha256}\"\n"
    );
    std::fs::write(&out, body)?;
    eprintln!("xtask: ghostty-web {version}, wasm sha256 {sha256}");
    Ok(out)
}

/// Decode the inlined wasm module and compare it against the file.
///
/// A difference means that the file and the bundle hold different modules. One
/// SHA-256 cannot then describe the build, so this is an error.
fn compare_inlined(esm: &Path, expected: &str) -> Result<()> {
    let Ok(text) = std::fs::read_to_string(esm) else {
        eprintln!("xtask: note: no ESM bundle at {}", esm.display());
        return Ok(());
    };
    let Some(start) = text.find(DATA_URI) else {
        eprintln!(
            "xtask: note: {} holds no inlined wasm module",
            esm.display()
        );
        return Ok(());
    };
    let payload: String = text[start + DATA_URI.len()..]
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '+' || *c == '/' || *c == '=')
        .collect();

    let bytes = base64_decode(&payload)?;
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    let got = format!("{:x}", hasher.finalize());
    if got != expected {
        return Err(format!(
            "the inlined wasm module in {} does not match ghostty-vt.wasm\n  \
             file    {expected}\n  inlined {got}",
            esm.display()
        )
        .into());
    }
    Ok(())
}

/// Decode standard base64. The alphabet is small and fixed, so a dependency for
/// this step is not necessary.
fn base64_decode(text: &str) -> Result<Vec<u8>> {
    let mut out: Vec<u8> = Vec::with_capacity(text.len() / 4 * 3);
    let mut acc: u32 = 0;
    let mut bits: u32 = 0;
    for c in text.bytes() {
        let value = match c {
            b'A'..=b'Z' => c - b'A',
            b'a'..=b'z' => c - b'a' + 26,
            b'0'..=b'9' => c - b'0' + 52,
            b'+' => 62,
            b'/' => 63,
            b'=' => break,
            other => return Err(format!("`{}` is not a base64 character", other as char).into()),
        };
        acc = (acc << 6) | u32::from(value);
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push((acc >> bits) as u8);
        }
    }
    Ok(out)
}
